### ISSUE TITLE
Custom chat drops input when typing too fast

### ISSUE THREAD

**Issue by gbMichelle** [Kavawuvi/chimera#9] opened 2019-12-20 06:44 UTC
I really don't type that fast. What's going on?

**Comment by Vaporeon** [comment] 2020-05-18 19:36
I can't reproduce this.

**Comment by Kavawuvi** [comment] 2020-07-29 05:45
Fixed in https://github.com/Kavawuvi/chimera/pull/33

**Closed by Kavawuvi** 2020-07-29 05:45 UTC
